### ISSUE TITLE
[1.20.4] Support multiple mod loaders within the repo

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundingsFabric#46]
### Overview
Goal is to implement a set of build and code changes to support building the mod for Fabric and Forge. Other mod loader environments will be added in the future (such as NeoForge).
 
### Task List
- [x] ~~Integrate Architectury plugin for multi plugin build~~
- [x] Mojang official mappings instead of Yarn
- [x] Support YACL as well as Cloth-Config API
- [ ] Utilize non-Architectury based project management system (https://github.com/jaredlll08/MultiLoader-Template)
- [ ] Get existing Fabric mod running using build system
- [ ] Add support for NeoForge
- [ ] Add support for Forge

**Comment by OreCruncher** [comment]
Related to Cloth-Config API - mod authors are keeping up with newer versions of MC but are not investing in additional features. Not sure the shape of Forge/NeoForge config UI yet.

**Comment by OreCruncher** [comment]
Abandoning this effort in favor of other options.
